stages:
  - build_and_publish
  - pull_and_run

build_and_publish:
  only:
    - staging
    - production
  stage: build_and_publish
  tags:
    - tailor
  before_script:
    - echo "$GITLAB_PWD" | sudo docker login -u "$GITLAB_UNAME" --password-stdin registry.gitlab.com
  script:
    - sudo docker build -t registry.gitlab.com/mectek/penjahit:$CI_COMMIT_BRANCH --build-arg branch=$CI_COMMIT_BRANCH .
    - sudo docker push registry.gitlab.com/mectek/penjahit:$CI_COMMIT_BRANCH

pull_and_run:
  only:
    - staging
  stage: pull_and_run
  tags:
    - tailor
  before_script:
    - echo "$GITLAB_PWD" | sudo docker login -u "$GITLAB_UNAME" --password-stdin registry.gitlab.com
  script:
    - cd deploy/$CI_COMMIT_BRANCH
    - sudo docker-compose pull
    - sudo docker-compose up -d
    - sudo docker image prune -f
