# docker-compose.yml

version: "3.7"
services:
  tailor_website:
    container_name: tailor_website
    restart: unless-stopped
    image: registry.gitlab.com/mectek/penjahit:staging
    ports:
      - "23081:8000"
    volumes:
      - cerah-storage:/var/www/storage
volumes:
  cerah-storage:
